### PR TITLE
Yashas

### PR DESCRIPTION
**Pull request by yashasm**

### CODE REVIEW

**Review by tejasgujjar — APPROVED** [review]

**Comment by tejasgujjar** [comment]
acceping yashas's change which updates homepage with backend loc data with rating directive

**Comment by ashwinangle30** [comment]
Guys,


I have created a mongodb connection so that we can have a common database.
Please connect to the same so all have the same data.

To test connection-

  In the terminal try -
  *mongo ds117311.mlab.com:17311/restreco
<http://ds117311.mlab.com:17311/restreco> -u restUser -p restUser123#*

To connect to DB in Node - We need to use mongoose

var mongoose = require('mongoose');
var mongourl = 'mongodb://*restUser*:*restUser123#*@
ds117311.mlab.com:17311/restreco';
mongoose.Promise = global.Promise;
mongoose.connect(mongourl);

-Ashwin Angle

**Comment by yashasm** [comment]
@ashwinangle30  
Since you have already done it, can you make changes in the mongodb.js in routes folder and check in. Just comment the code and insert new connection detail. We will pull the latest code. 

Please make sure you only change the connection detail in mongodb.js

**Comment by tejasgujjar** [comment]
@ashwinangle30 
Thank you Ashwin, we 've achieved a major milestone today. Please add anyone of us as assignee before merging the code. 

-Tejas

**Comment by ashwinangle30** [comment]
Sure, I will do it and push the changes in my branch and make a pull
request to master. Or should I directly push to master??

**Comment by yashasm** [comment]
Do it to your branch and create pull request

**Comment by yashasm** [comment]
And make one of us as assignee to your pull request

**Pull request merged**
